name: Tests Python et Déploiement

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    
    - name: Run pytest
      run: pytest

  deploiement:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Déployer sur EC2
      env:
        HOST: ec2-13-60-25-39.eu-north-1.compute.amazonaws.com
        USER: ubuntu
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        
        # Configurer l'agent SSH
        eval $(ssh-agent -s)
        echo "${{ secrets.EC2_PRIVATE_KEY_FILE }}" | base64 --decode > key-pair_v2.pem
        chmod 600 key-pair_v2.pem
        ssh-add key-pair_v2.pem
        
        ssh -o StrictHostKeyChecking=no ${USER}@${HOST} << EOF
          cd Projet_7_Modele_de_scoring
          
          # Vérifier la version de Python sur EC2
          python3 -c "import sys; required_version = (3, 12, 3); current_version = sys.version_info[:3]; exit(1) if current_version < required_version else exit(0)"
          
          if [ $? -ne 0 ]; then
            echo "Erreur : La version de Python sur l'instance EC2 est inférieure à 3.12.3"
            exit 1
          fi
          
          # Activer l'environnement virtuel
          source env/bin/activate
          
          # Mettre à jour le code avec le dernier commit
          git pull
          
          # Installer ou mettre à jour les dépendances
          pip install -r requirements.txt
          
          # Arrêter les processus existants (si nécessaire)
          pkill -f "python api.py"
          pkill -f "streamlit run app_dashboard.py"
          
          # Lancer l'API
          nohup python api.py > api.log 2>&1 &
          
          # Lancer le dashboard Streamlit
          nohup streamlit run app_dashboard.py > streamlit.log 2>&1 &
          
          echo "Déploiement terminé"
        EOF